# -*- coding: utf-8 -*-
"""Taiyo_Scrapper.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DK9xUgWFGHCJV2Rc-loxN636kcHR9q-3
"""

import requests
from bs4 import BeautifulSoup
import pandas as pd

class WebScraping:
  def __init__(self):
    url = 'https://dot.ca.gov/programs/procurement-and-contracts/contracts-out-for-bid'
    response = requests.get(url)

    soup = BeautifulSoup(response.content, 'html.parser')
    stat_table = soup.find('table', class_= 'table')

    res=[]
    for row in stat_table.find_all('tr'):
      td = row.find_all('td')
      tr = [row.text.strip() for row in td if row.text.strip()]
      if tr:
        res.append(tr)
    
    df = pd.DataFrame(res, columns=["Event ID", "Event Name", "End Date"])
    print(df)

    df.to_csv('California_Procurement.csv',index = False)
    print('Web Scraping Successful!')

ws = WebScraping()